defaults:
  - /slam: default

instance: vipe.pipeline.default.DefaultAnnotationPipeline

# Init configs
init:
  camera_type: "pinhole"
  intrinsics: "geocalib"
  instance: null
    # kf_gap_sec: 2.0
    # phrases: 
    #   - person
    # add_sky: false

slam:
  keyframe_depth: unidepth-l
  optimize_intrinsics: ${neq:${..init.intrinsics},"gt"}
  visualize: true
  model_family: "radseg"
  model_variant: "c-radio_v3-b"
  radseg_lang_model: "siglip2"
  radseg_slide_crop: 336
  radseg_slide_stride: 224
  radseg_lang_align: True
  pca_dim: 256
  pca_state_path: vipe_results/vipe

# Post-processing configs
post:
  depth_align_model: "adaptive_unidepth-l_svda"

# Output configs
output:
  # Path to save results
  path: vipe_results/
  skip_exists: false

  # Save artifacts and a info file
  save_artifacts: false
  save_slam_map: true

  # Visualization videos to BASE_PATH/vipe/xxx.mp4
  save_viz: true
  viz_downsample: 2
  viz_attributes: [['rgb', 'embedding'], ['depth', 'pcd']]
